### ISSUE TITLE
Custom Webhook Script

### ISSUE THREAD

**Issue by Pubbo21** [CGray1234/Roblox-Webhook-System#1]
Hey, would it be possible for you to help me with making a script, where when a player clicks on a button in my GUI, it sends a webhook to discord with the players name and a title? Need it for my group.

**Comment by CGray1234** [comment]
Shoot sorry that I didn't see this, GitHub never sent me an email. But yeah I gotchu

### This is a bit more complicated than just a PlayerAdded method, so you will need to:

1. Create a RemoteEvent and name it SendWebhookEvent. Put that in Replicated storage.

2. Create a LocalScript and parent it to the button. Put this following code into the script:


```
local player = game:GetService("Players").LocalPlayer

local RemoteEvent = game:GetService("ReplicatedStorage").SendWebhookEvent

local button = script.Parent

button.MouseButton1Click:Connect(function()
	
       RemoteEvent:FireServer(player)
end)

```


3. Put a Script into ServerScriptService. Put the following code into the script:

```
local RemoteEvent = game:GetService("ReplicatedStorage").SendWebhookEvent

RemoteEvent.OnServerEvent:Connect(function(player)
	
	local plrName = player.Name
	
	local webhookURL = "https://hooks.hyra.io/api/webhooks/xxxxxxxxx/xxxxxxxxxx" --Replace all "x" with the webhook URL. DO NOT CHANGE hooks.hyra.io!!! DOING SO WILL BREAK IT! More info here: https://devforum.roblox.com/t/discord-webhook-proxy/1500688
	local HttpService = game:GetService("HttpService")
	
		--Add whatever you want right here, if you would like me to make a script designed so that when a player chats a command or anything, please create an issue in the issues tab
	local data = {
		["embeds"] = {{
			["title"] = plrName.." clicked a button",
			["description"] = "Message here"
		}}
	}
	
	
	local encodedData = HttpService:JSONEncode(data)
	HttpService:PostAsync(webhookURL, encodedData)
end)
```

And then you're done! Comment if you have any questions or issues. This issue will be closed
